{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9596ab73-b6c5-498e-a162-771b4f53a60f",
   "metadata": {},
   "outputs": [],
   "source": [
    "# generate_insights.py\n",
    "import os\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "\n",
    "# =====================================================================\n",
    "# 1. GLOBAL DESIGN CONFIGURATION (The Editor & Architect Principles)\n",
    "# =====================================================================\n",
    "# Clean typography and minimal ink ratios according to project blueprint\n",
    "plt.rcParams['font.family'] = 'sans-serif'\n",
    "plt.rcParams['text.color'] = '#333333'\n",
    "plt.rcParams['axes.labelcolor'] = '#333333'\n",
    "plt.rcParams['xtick.color'] = '#333333'\n",
    "plt.rcParams['ytick.color'] = '#333333'\n",
    "sns.set_theme(style=\"white\")\n",
    "\n",
    "def load_and_clean_data(file_path):\n",
    "    \"\"\"Loads dataset and performs essential data mitigation and parsing.\"\"\"\n",
    "    if not os.path.exists(file_path):\n",
    "        raise FileNotFoundError(\n",
    "            f\"Could not find the dataset file: '{file_path}'. \"\n",
    "            \"Please ensure it is placed in the exact same directory as this script.\"\n",
    "        )\n",
    "        \n",
    "    print(f\"🔄 Processing File: {file_path}...\")\n",
    "    df = pd.read_csv(file_path)\n",
    "    \n",
    "    # Structural normalization\n",
    "    df['Date'] = pd.to_datetime(df['Date'])\n",
    "    df['YearMonth'] = df['Date'].dt.to_period('M')\n",
    "    \n",
    "    # Gracefully handling missing values instead of losing analytical rows\n",
    "    df['CouponCode'] = df['CouponCode'].fillna('No Coupon Code Used')\n",
    "    \n",
    "    print(\"✅ System integrity verified. Data loaded successfully.\")\n",
    "    return df\n",
    "\n",
    "def generate_analytical_suite(df, output_folder='output_charts'):\n",
    "    \"\"\"Generates and archives executive boardroom visualizations.\"\"\"\n",
    "    print(f\"📊 Starting visualization engine. Exporting files to '{output_folder}/'...\")\n",
    "    os.makedirs(output_folder, exist_ok=True)\n",
    "    \n",
    "    # -------------------------------------------------------------\n",
    "    # CHART 1: Monthly Revenue Trajectory (Temporal Trend)\n",
    "    # -------------------------------------------------------------\n",
    "    plt.figure(figsize=(11, 5))\n",
    "    monthly_sales = df.groupby('YearMonth')['TotalPrice'].sum().reset_index()\n",
    "    monthly_sales['YearMonth'] = monthly_sales['YearMonth'].astype(str)\n",
    "    \n",
    "    plt.plot(monthly_sales['YearMonth'], monthly_sales['TotalPrice'], marker='o', color='#1a5f7a', linewidth=2.5)\n",
    "    plt.title(\"Monthly Revenue Trajectory (2023 - 2025)\", fontsize=13, fontweight='bold', pad=15, loc='left')\n",
    "    plt.xlabel(\"Timeline (Months)\", fontsize=10)\n",
    "    plt.ylabel(\"Total Revenue ($)\", fontsize=10)\n",
    "    plt.xticks(rotation=45)\n",
    "    plt.grid(axis='y', linestyle='--', alpha=0.5)\n",
    "    sns.despine()\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(f'{output_folder}/chart1_revenue_trend.png', dpi=300)\n",
    "    plt.close()\n",
    "\n",
    "    # -------------------------------------------------------------\n",
    "    # CHART 2: Product Performance Contribution (Horizontal Bar)\n",
    "    # -------------------------------------------------------------\n",
    "    plt.figure(figsize=(10, 5))\n",
    "    product_sales = df.groupby('Product')['TotalPrice'].sum().sort_values(ascending=True)\n",
    "    # Spotlight focus color configuration: High contrast for max earner\n",
    "    colors = ['#d3d3d3' if x < product_sales.max() else '#1a5f7a' for x in product_sales]\n",
    "    \n",
    "    product_sales.plot(kind='barh', color=colors, width=0.7)\n",
    "    plt.title(\"Product Revenue Contribution: Category Analysis\", fontsize=13, fontweight='bold', pad=15, loc='left')\n",
    "    plt.xlabel(\"Total Revenue ($)\", fontsize=10)\n",
    "    plt.ylabel(\"Product Category\", fontsize=10)\n",
    "    sns.despine(left=True, bottom=True)\n",
    "    plt.grid(axis='x', linestyle='--', alpha=0.5)\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(f'{output_folder}/chart2_product_performance.png', dpi=300)\n",
    "    plt.close()\n",
    "\n",
    "    # -------------------------------------------------------------\n",
    "    # CHART 3: Acquisition Mix Share (Donut Chart)\n",
    "    # -------------------------------------------------------------\n",
    "    plt.figure(figsize=(6, 6))\n",
    "    referral_sales = df.groupby('ReferralSource')['TotalPrice'].sum()\n",
    "    traffic_colors = ['#1a5f7a', '#57c5b6', '#159897', '#002b5b', '#a0c4ff']\n",
    "    \n",
    "    plt.pie(referral_sales, labels=referral_sales.index, autopct='%1.1f%%', \n",
    "            startangle=140, colors=traffic_colors, wedgeprops=dict(width=0.4, edgecolor='w'))\n",
    "    plt.title(\"Revenue Share by Referral Channel\", fontsize=13, fontweight='bold', pad=20, loc='center')\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(f'{output_folder}/chart3_referral_share.png', dpi=300)\n",
    "    plt.close()\n",
    "\n",
    "    # -------------------------------------------------------------\n",
    "    # CHART 4: Operational Logistical Health (Categorical Status)\n",
    "    # -------------------------------------------------------------\n",
    "    plt.figure(figsize=(10, 5))\n",
    "    status_counts = df['OrderStatus'].value_counts()\n",
    "    # Strategic color codes: Green for revenue captured, Red for revenue at loss risk\n",
    "    status_colors = ['#2b9348' if x in ['Delivered', 'Shipped'] else '#d90429' for x in status_counts.index]\n",
    "    \n",
    "    sns.barplot(x=status_counts.values, y=status_counts.index, palette=status_colors, hue=status_counts.index)\n",
    "    plt.title(\"Operational Status: Tracking Order Fulfillment vs Revenue Risk\", fontsize=13, fontweight='bold', pad=15, loc='left')\n",
    "    plt.xlabel(\"Number of Orders\", fontsize=10)\n",
    "    plt.ylabel(\"Order Status\", fontsize=10)\n",
    "    sns.despine()\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(f'{output_folder}/chart4_order_status.png', dpi=300)\n",
    "    plt.close()\n",
    "\n",
    "    # -------------------------------------------------------------\n",
    "    # CHART 5: Feature Inter-dependencies (Correlation Heatmap)\n",
    "    # -------------------------------------------------------------\n",
    "    plt.figure(figsize=(8, 6))\n",
    "    numerical_cols = df[['Quantity', 'UnitPrice', 'ItemsInCart', 'TotalPrice']]\n",
    "    correlation_matrix = numerical_cols.corr()\n",
    "    \n",
    "    sns.heatmap(correlation_matrix, annot=True, cmap='Blues', fmt=\".2f\", linewidths=0.5, cbar=False)\n",
    "    plt.title(\"Correlation Matrix: Cart Metrics vs. Total Revenue\", fontsize=13, fontweight='bold', pad=15, loc='left')\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(f'{output_folder}/chart5_correlation_heatmap.png', dpi=300)\n",
    "    plt.close()\n",
    "\n",
    "    # -------------------------------------------------------------\n",
    "    # CHART 6: Pricing Tier Architecture Spread (Box Plot)\n",
    "    # -------------------------------------------------------------\n",
    "    plt.figure(figsize=(10, 6))\n",
    "    product_order = df.groupby('Product')['UnitPrice'].median().sort_values(ascending=False).index\n",
    "    \n",
    "    sns.boxplot(data=df, x='UnitPrice', y='Product', order=product_order, palette='Blues_r', hue='Product', legend=False)\n",
    "    plt.title(\"Product Price Spreads: Identifying Premium vs Standard SKUs\", fontsize=13, fontweight='bold', pad=15, loc='left')\n",
    "    plt.xlabel(\"Unit Price ($)\", fontsize=10)\n",
    "    plt.ylabel(\"Product\", fontsize=10)\n",
    "    sns.despine()\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(f'{output_folder}/chart6_price_distribution.png', dpi=300)\n",
    "    plt.close()\n",
    "\n",
    "    # -------------------------------------------------------------\n",
    "    # CHART 7: Payment Engine Shifts Over Timeline (Multi-Line)\n",
    "    # -------------------------------------------------------------\n",
    "    plt.figure(figsize=(11, 5))\n",
    "    df_sorted = df.sort_values('YearMonth')\n",
    "    df_sorted['YearMonth_Str'] = df_sorted['YearMonth'].astype(str)\n",
    "    payment_trends = df_sorted.groupby(['YearMonth_Str', 'PaymentMethod']).size().unstack(fill_value=0)\n",
    "    \n",
    "    for column in payment_trends.columns:\n",
    "        plt.plot(payment_trends.index, payment_trends[column], marker='o', label=column, linewidth=2)\n",
    "        \n",
    "    plt.title(\"Payment Preference Evolution over Time\", fontsize=13, fontweight='bold', pad=15, loc='left')\n",
    "    plt.xlabel(\"Timeline\", fontsize=10)\n",
    "    plt.ylabel(\"Number of Transactions\", fontsize=10)\n",
    "    plt.xticks(rotation=45)\n",
    "    plt.legend(frameon=False, loc='upper left')\n",
    "    plt.grid(axis='y', linestyle='--', alpha=0.3)\n",
    "    sns.despine()\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(f'{output_folder}/chart7_payment_trends.png', dpi=300)\n",
    "    plt.close()\n",
    "\n",
    "    # -------------------------------------------------------------\n",
    "    # CHART 8: Coupon Code Campaign Performance (Bar Chart)\n",
    "    # -------------------------------------------------------------\n",
    "    plt.figure(figsize=(10, 5))\n",
    "    coupon_revenue = df.groupby('CouponCode')['TotalPrice'].sum().sort_values(ascending=False)\n",
    "    # Spotlights the best executing coupon campaign (index 1 assuming 'No Coupon' is top)\n",
    "    coupon_colors = ['#1a5f7a' if x == coupon_revenue.index[1] else '#d3d3d3' for x in coupon_revenue.index]\n",
    "    \n",
    "    sns.barplot(x=coupon_revenue.values, y=coupon_revenue.index, palette=coupon_colors, hue=coupon_revenue.index, legend=False)\n",
    "    plt.title(\"Campaign Impact: Gross Revenue Generated via Promotional Codes\", fontsize=13, fontweight='bold', pad=15, loc='left')\n",
    "    plt.xlabel(\"Gross Revenue ($)\", fontsize=10)\n",
    "    plt.ylabel(\"Coupon Code Applied\", fontsize=10)\n",
    "    sns.despine"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
